// The runtime dispatcher source, embedded as a string so a single tsup bundle
// can write it to .claude/wisp-rulecast/dispatch.mjs without depending on an
// external `assets/` directory at runtime.
//
// The dispatcher itself runs INSIDE the user's project as a PreToolUse hook.
// It reads its rule from .claude/wisp-rulecast/rules.json, checks the
// tool_input from stdin, and emits a structured allow/deny decision.

export const DISPATCHER_SOURCE = `#!/usr/bin/env node
// Generated by wisp-rulecast. Do not edit by hand.
// Re-run \`wisp-rulecast compile\` to regenerate.

import { appendFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, isAbsolute, join, resolve, sep } from "node:path";

const projectDir = process.env.CLAUDE_PROJECT_DIR || process.cwd();
const wispDir = join(projectDir, ".claude", "wisp-rulecast");
const rulesPath = join(wispDir, "rules.json");
const statePath = join(wispDir, "state.json");
const logPath = join(projectDir, ".claude", "wisp-rulecast.log");

function getArg(name) {
  const i = process.argv.indexOf(name);
  return i >= 0 ? process.argv[i + 1] : undefined;
}

function readStdinSync() {
  try {
    return readFileSync(0, "utf8");
  } catch {
    return "";
  }
}

function loadJson(p, fallback) {
  if (!existsSync(p)) return fallback;
  try {
    return JSON.parse(readFileSync(p, "utf8"));
  } catch {
    return fallback;
  }
}

function saveJson(p, value) {
  mkdirSync(dirname(p), { recursive: true });
  writeFileSync(p, JSON.stringify(value, null, 2));
}

function audit(entry) {
  try {
    mkdirSync(dirname(logPath), { recursive: true });
    appendFileSync(logPath, JSON.stringify(entry) + "\\n");
  } catch {
    // logging must never fail the hook
  }
}

function allow() {
  process.exit(0);
}

function deny(rule, reason, toolName, toolInput) {
  const where = rule.source ? \`(\${rule.source.file}:\${rule.source.line})\` : "";
  const message = \`wisp-rulecast: \${reason} \${where}\`.trim();
  audit({
    ts: new Date().toISOString(),
    rule: rule.id,
    kind: rule.kind,
    tool: toolName,
    input: toolInput,
    decision: "deny",
    reason: message,
  });
  process.stdout.write(
    JSON.stringify({
      hookSpecificOutput: {
        hookEventName: "PreToolUse",
        permissionDecision: "deny",
        permissionDecisionReason: message,
      },
    }) + "\\n",
  );
  process.exit(0);
}

function normalizePath(p) {
  if (!p) return "";
  const abs = isAbsolute(p) ? p : resolve(projectDir, p);
  return abs.split(sep).join("/");
}

function patternMatches(pattern, target) {
  if (!pattern || !target) return false;
  const t = target.toLowerCase();
  const p = pattern.toLowerCase();
  if (p.startsWith("*.")) {
    return t.endsWith(p.slice(1));
  }
  if (p.startsWith("*")) {
    return t.includes(p.slice(1));
  }
  return t.includes(p);
}

function pathInside(target, allowed) {
  const t = normalizePath(target).toLowerCase();
  const a = normalizePath(allowed).toLowerCase();
  return t === a || t.startsWith(a.endsWith("/") ? a : a + "/");
}

function commandMatches(commandLine, pattern) {
  if (!commandLine || !pattern) return false;
  const c = commandLine.toLowerCase();
  const p = pattern.toLowerCase();
  return c.includes(p);
}

function checkNeverCommit(rule, toolInput) {
  if ((toolInput.command || "").toLowerCase().includes("git commit") ||
      (toolInput.command || "").toLowerCase().includes("git add") ||
      (toolInput.command || "").toLowerCase().includes("git push") ||
      (toolInput.command || "").toLowerCase().includes("git stash")) {
    const cmd = String(toolInput.command || "");
    if (commandMatches(cmd, rule.params.pattern)) {
      return \`NEVER commit \${rule.params.pattern}\`;
    }
  }
  return null;
}

function checkNeverEditPath(rule, toolInput) {
  const fp = normalizePath(toolInput.file_path || "");
  const pattern = rule.params.pathPattern;
  if (patternMatches(pattern, fp) || pathInside(fp, pattern)) {
    return \`NEVER edit \${pattern}\`;
  }
  return null;
}

function checkNeverRunCmd(rule, toolInput) {
  const cmd = String(toolInput.command || "");
  if (commandMatches(cmd, rule.params.commandPattern)) {
    return \`NEVER run \${rule.params.commandPattern}\`;
  }
  return null;
}

function checkAllowlistPaths(rule, toolInput) {
  const fp = normalizePath(toolInput.file_path || "");
  if (!fp) return null;
  const ok = rule.params.allowedPaths.some((p) => pathInside(fp, p) || patternMatches(p, fp));
  if (!ok) {
    return \`ONLY write inside: \${rule.params.allowedPaths.join(", ")}\`;
  }
  return null;
}

function recordPrecondition(rule) {
  const state = loadJson(statePath, { markers: {} });
  state.markers = state.markers || {};
  state.markers[rule.id] = Date.now();
  saveJson(statePath, state);
}

function checkAlwaysBefore(rule, toolInput) {
  const cmd = String(toolInput.command || "").toLowerCase();
  if (!cmd.includes(rule.params.action.toLowerCase())) return null;
  const state = loadJson(statePath, { markers: {} });
  const ts = state.markers && state.markers[rule.id];
  if (!ts) {
    return \`ALWAYS \${rule.params.precondition} before \${rule.params.action} (marker not set this session)\`;
  }
  return null;
}

function main() {
  const ruleId = getArg("--rule");
  if (!ruleId) allow();

  const stdin = readStdinSync();
  let event;
  try {
    event = JSON.parse(stdin || "{}");
  } catch {
    allow();
    return;
  }

  const registry = loadJson(rulesPath, { rules: [] });
  const rule = (registry.rules || []).find((r) => r.id === ruleId);
  if (!rule) allow();

  const toolInput = event.tool_input || {};
  const toolName = event.tool_name || "";
  const eventName = event.hook_event_name || "";

  if (rule.kind === "always-before" && eventName === "PostToolUse") {
    const cmd = String(toolInput.command || "").toLowerCase();
    if (cmd.includes(rule.params.precondition.toLowerCase())) {
      recordPrecondition(rule);
    }
    allow();
    return;
  }

  let reason = null;
  switch (rule.kind) {
    case "never-commit":
      reason = checkNeverCommit(rule, toolInput);
      break;
    case "never-edit-path":
      reason = checkNeverEditPath(rule, toolInput);
      break;
    case "never-run-cmd":
      reason = checkNeverRunCmd(rule, toolInput);
      break;
    case "always-before":
      reason = checkAlwaysBefore(rule, toolInput);
      break;
    case "allowlist-paths":
      reason = checkAllowlistPaths(rule, toolInput);
      break;
  }

  if (reason) deny(rule, reason, toolName, toolInput);
  allow();
}

main();
`;
